### ISSUE TITLE
Filamet V3

### ISSUE THREAD

**Issue by flolanger** [aymanalhattami/filament-page-with-sidebar#13]
Because Filament V3 still doesn't provide a native way to have a page sidebar, it would be awesome if this package would support the new upcoming V3 version.

Thank you so much for your work!

**Comment by aeq-dev** [comment]
+1

**Comment by faizananwerali** [comment]
+1

**Comment by aymanalhattami** [comment]
Support for filament v3 will be on this weekend

**Comment by aymanalhattami** [comment]
filament v3 supported

**Comment by aeq-dev** [comment]
Thanks dear @aymanalhattami
