### ISSUE TITLE
Documentation needs improvement.

### ISSUE THREAD

**Issue by rahat1994** [aymanalhattami/filament-page-with-sidebar#14]
I am tinkering with Filament for the last 2 days. And I needed a multilevel menu and found this package via Laravel daily. Its a great and versatile package but I had to go through the demo project to figure out how things worked.

So I think introducing some steps in the usage section will greatly improve the user experience.

Great package by the way and thanks for your work.

**Comment by aymanalhattami** [comment]
There is a demo project

https://github.com/aymanalhattami/filament-page-with-sidebar-project

**Comment by soixt** [comment]
He just said he needs to go through the **DEMO PROJECT** to find out how does it work, so did I. Better steps should be made in the docs. Not the demo project..
