### ISSUE TITLE
demo project for filament v3?

### ISSUE THREAD

**Issue by faizananwerali** [aymanalhattami/filament-page-with-sidebar#15]
demo project for filament v3? the current demo project is still for filament v2, which no longer works with filament v3 because views doesn't work on them, can you please update them?

**Comment by aymanalhattami** [comment]
For Filament 2.x use [filament-v2 branch](https://github.com/aymanalhattami/filament-page-with-sidebar-project/tree/filament-v2)

For Filament 3.x use [main branch](https://github.com/aymanalhattami/filament-page-with-sidebar-project/)
