### ISSUE TITLE
Collapsible sidebar

### ISSUE THREAD

**Issue by Dontorpedo** [aymanalhattami/filament-page-with-sidebar#2]
is it or will it be possible to make the sidebar collapsible?

thanks

**Comment by akunbeben** [comment]
I see it is collapsible and inherits the behavior of the filament.sidebar element, but I think it would be very nice to have independent collapsible behavior on it. 

I've tested it here 
<details><summary>Normal</summary>
<p>

![image](https://user-images.githubusercontent.com/46495960/233455376-0a50cce9-60f3-4a81-aacc-cd5d0c43c489.png)

</p>
</details> 

<details><summary>Collapsed</summary>
<p>

![image](https://user-images.githubusercontent.com/46495960/233455430-4ea1092c-9a90-431c-be71-f9c24c68f6ed.png)

</p>
</details> 

Still figuring out how I can achieve this, I will create a PR if I find a good solution.

**Comment by aymanalhattami** [comment]
Ok, I will fix it.

Or if you found a solution, you can make PR

**Comment by aymanalhattami** [comment]
It has been fixed

**Comment by KamranBiglari** [comment]
@aymanalhattami 
I have an issue with collapsed.
Version 2.6

![Image](https://github.com/user-attachments/assets/88b851fb-f770-467b-97cb-a54c0a024198)
