### ISSUE TITLE
[IDEA] Support custom pages

### ISSUE THREAD

**Issue by mohamedsabil83** [aymanalhattami/filament-page-with-sidebar#27]
Hi @aymanalhattami, thank you for the great package.

I suggest you support custom pages also. Every project had some pages unrelated to **resource** but related to the same aim, like setting pages. It'll be helpful to sort these pages together.

**Comment by aymanalhattami** [comment]
I am working on it

**Comment by mohamedsabil83** [comment]
Can you mention it here when it ready? I'll be sure to follow up on any updates but in case.

**Comment by aymanalhattami** [comment]
Check version 2.2.0

https://github.com/aymanalhattami/filament-page-with-sidebar#usage-with-page

**Comment by mohamedsabil83** [comment]
Great work, @aymanalhattami. On time. I'll try it today in a new project I am working on.
