### ISSUE TITLE
Issue with sm view

### ISSUE THREAD

**Issue by fouteox** [aymanalhattami/filament-page-with-sidebar#28]
https://github.com/aymanalhattami/filament-page-with-sidebar/blob/ffdf55c391a773e7c9024ba181f7e1501e1bc3f5/resources/views/components/page.blade.php#L74

When the media querie is on sm, the display bugs, see the first screen.

By commenting on this line, everything returns to normal like the second screen.

<img width="826" alt="Capture d’écran 2023-10-06 à 20 25 24" src="https://github.com/aymanalhattami/filament-page-with-sidebar/assets/88294294/d16a0edf-b9a3-49fc-a3b4-5a42ab6ef892">

<img width="854" alt="Capture d’écran 2023-10-06 à 20 26 58" src="https://github.com/aymanalhattami/filament-page-with-sidebar/assets/88294294/68da6613-41ee-47da-8e12-0d9b799f925d">

**Comment by aymanalhattami** [comment]
PRs are welcomes

**Comment by fouteox** [comment]
@aymanalhattami CSS is not my strong suit.

The commented out line that removes this bug seems to be a default setting, and I don't know how to explain the problem.
