### ISSUE TITLE
SetTitle() Light Mode

### ISSUE THREAD

**Issue by koppa53** [aymanalhattami/filament-page-with-sidebar#29]
![image](https://github.com/aymanalhattami/filament-page-with-sidebar/assets/72752456/c1c1341a-13d6-4e89-9648-83147927ed07)
Light Mode

![image](https://github.com/aymanalhattami/filament-page-with-sidebar/assets/72752456/533c0145-e545-4eb7-a7a9-2bd5ebf2f6aa)
Dark Mode

```
use AymanAlhattami\FilamentPageWithSidebar\FilamentPageSidebar;
use AymanAlhattami\FilamentPageWithSidebar\PageNavigationItem;
public static function sidebar(Model $record): FilamentPageSidebar
    {
        return FilamentPageSidebar::make()
            ->setTitle($record->name)
            ->setDescription($record->email)
            ->setNavigationItems([
                PageNavigationItem::make('View User')
                    ->url(function () use ($record) {
                        return static::getUrl('view', ['record' => $record->id]);
                    }),
            ]);
    }
```
Source Code

**Not Visible when in light mode.** Currently using Filament v.3.0.102.

**Comment by aymanalhattami** [comment]
Upgrade to latest version

**Comment by koppa53** [comment]
> Upgrade to latest version

My plug-in is already at version version 2.4.2. Also tried clearing cache nothing happens.

**Comment by kszyrvercobrador** [comment]
Same issue on my end, version 2.4.2
