### ISSUE TITLE
Display/CSS Issue with Initial Setup

### ISSUE THREAD

**Issue by dreamfast** [aymanalhattami/filament-page-with-sidebar#32]
Hi there, thanks for making this package. I've setup the package as per the instructions, however there seems to be a display or CSS issue with how the menus are displayed. The top bar also is missing the styles.

They do not match the screenshots in the readme, and can't seem to pickup the existing styles.

I can also see that `public/css/aymanalhattami/filament-page-with-sidebar/filament-page-with-sidebar.css` is published.

Using version 2.4.2.

![image](https://github.com/aymanalhattami/filament-page-with-sidebar/assets/5360978/533a21ad-fae5-4a67-b8c1-b2b1500770e4)

**Comment by aymanalhattami** [comment]
It functions as promised.

Verify that no CSS is installed on your system that conflicts with this package.
