### ISSUE TITLE
The active item loses the activity indication when working with components

### ISSUE THREAD

**Issue by krio-rogue** [aymanalhattami/filament-page-with-sidebar#36]
Package version : `2.4.2`

On first open page, menu item has indication "active", on work with any components (table filters, sorting, trigger button actions) menu item loses indication.
```
->isActiveWhen(function () {
    return request()->routeIs(static::getRouteBaseName() . '.activities.user');
})
```
Filament package has "Sub Navigation", and when you update components, its state remains unchanged. This can be clearly seen if you use, for example, this code 
```
->label(function() {
    return request()->route()->getName() . ' | ' . microtime(true);
})
```

Steps to reproduce
Repo : https://github.com/aymanalhattami/filament-page-with-sidebar-project
Url : http://127.0.0.1:8000/admin/users/1/activities/user
Open page  "User Activities", menu item  "User Activities" has indication "active".
On click 'View' button on any record, a modal popup will be open.
Close modal popup.
Current menu item "User Activities" without indication "active".

**Comment by aymanalhattami** [comment]
It works


https://github.com/aymanalhattami/filament-page-with-sidebar/assets/34315778/8be5be26-997c-42ee-997f-bb25fb3e5e5e

**Comment by krio-rogue** [comment]
@aymanalhattami https://github.com/aymanalhattami/filament-page-with-sidebar-project/blob/main/app/Filament/Resources/UserResource.php not enabled `sidebarNavigation` mode.
Just checked the code in the repository (https://github.com/aymanalhattami/filament-page-with-sidebar-project) , when  `sidebar` mode is enabled, the indication is preserved. 
When `top` is enabled, the indication is lost.

**Comment by sandifb** [comment]
same issue for topbarNavigation()
