### ISSUE TITLE
SPA mode

### ISSUE THREAD

**Issue by patrickhoogkamer** [aymanalhattami/filament-page-with-sidebar#39]
It seems there is no support for SPA mode, is that correct? When we enable SPA mode the page sidebar is not adding `wire:navigate` to the items.

Or did I miss a setting for it?

**Comment by alisalehi1380** [comment]
I use SPA and I have no problem.

**Comment by aymanalhattami** [comment]
fixed on [2.5.2](https://github.com/aymanalhattami/filament-page-with-sidebar/releases/tag/2.5.2)
