### ISSUE TITLE
Error in define a $record property in each custom page

### ISSUE THREAD

**Issue by fabianosfbr** [aymanalhattami/filament-page-with-sidebar#4]
When to set a $record property on each custom page this error

`Type of App\Filament\Resources\IssuerResource\Pages\EditIssuer::$record must not be defined (as in class Filament\Resources\Pages\EditRecord)`

and the Demo Project Link not working

Tks

**Comment by aymanalhattami** [comment]
You do not need to define $record If your EditIssuer extends Filament\Resources\Pages\EditRecord


[Demo link](https://github.com/aymanalhattami/filament-page-with-sidebar-project)
