### ISSUE TITLE
wrong default layout in README file

### ISSUE THREAD

**Issue by alisalehi1380** [aymanalhattami/filament-page-with-sidebar#40]
in README file : 
![image](https://github.com/aymanalhattami/filament-page-with-sidebar/assets/111766206/b48c70e2-011c-45f3-baf4-273ad12b37da)

but : 
https://github.com/aymanalhattami/filament-page-with-sidebar/blob/90469a3a1563918d7fb06d56663590efe17f25b8/src/FilamentPageSidebar.php#L20

isn't default layout topbar?!
I think I should change the default layout in the FilamentPageSidebar file. can I fix it by PR?

**Comment by aymanalhattami** [comment]
Yeah you are right
PR are welcome
