### ISSUE TITLE
Wrong calculate filament content in `sm` screen size

### ISSUE THREAD

**Issue by alisalehi1380** [aymanalhattami/filament-page-with-sidebar#41]
Or it should be removed altogether. Or this is better in my opinion. Because this problem exists only in 12.

```--col-span-sm: span {{ $sidebarWidths['sm'] == 12 ? 12 : 12 - $sidebarWidths['sm'] }};```

https://github.com/aymanalhattami/filament-page-with-sidebar/blob/90469a3a1563918d7fb06d56663590efe17f25b8/resources/views/components/page.blade.php#L72

The problem video was emailed due to high volume 📧

@faizananwerali Do you have an idea how to fix it?

**Comment by aymanalhattami** [comment]
fixed on [2.5.2](https://github.com/aymanalhattami/filament-page-with-sidebar/releases/tag/2.5.2)
