### ISSUE TITLE
Problem with style

### ISSUE THREAD

**Issue by damaskus92** [aymanalhattami/filament-page-with-sidebar#43]
![Screenshot from 2024-07-31 17-38-58](https://github.com/user-attachments/assets/76e2301a-3038-4654-b9c2-5a115a148648)

![Screenshot from 2024-07-31 17-40-15](https://github.com/user-attachments/assets/a7b6689f-8c3c-4979-88be-270e8590b02a)

How to get package css styles?

**Comment by aymanalhattami** [comment]
No need to add the style manually, it includes by default like filament styles,
