### ISSUE TITLE
Dropdown for mobile view

### ISSUE THREAD

**Issue by onursahindur** [aymanalhattami/filament-page-with-sidebar#5]
Hello,

Thanks for a great plugin. 
You saved a lot of time and effort for us.

I have a question about is it possible to make a quick mobile view for this plugin?
When the list gets bigger, it is more complex on mobile. For example;

<img width="450" alt="Screenshot 2023-05-16 at 17 42 35" src="https://github.com/aymanalhattami/filament-page-with-sidebar/assets/5830807/a040df19-9192-4180-8e1c-45753f540189">

Maybe it is useful to put a dropdown when mobile view is enabled is a better approach.
I have limited CSS knowledge, because of that I opened an issue.
Do you have a quick solution for this?

Thanks.

**Comment by faizananwerali** [comment]
+1

**Comment by aymanalhattami** [comment]
Thanks for you feedback and suggestions 

I cannot guarantee that all feature requests will be implemented, but I will do my best to consider every suggestion

If you have any experience with coding or development, pull requests are welcome from the community to help me improve the package.
