### ISSUE TITLE
No publishable resources for tag [filament-page-with-sidebar-components].  

### ISSUE THREAD

**Issue by danilogiacomi** [aymanalhattami/filament-page-with-sidebar#9]
When running the  
`php artisan vendor:publish --tag="filament-page-with-sidebar-components"`
command, nothing is done, and the message 

   INFO  No publishable resources for tag [filament-page-with-sidebar-components].  

is returned

**Comment by aymanalhattami** [comment]
There is no components to be published, README file will be updated.


you can publish

`php artisan vendor:publish --tag="filament-page-with-sidebar-config"`

`php artisan vendor:publish --tag="filament-page-with-sidebar-views"`

**Comment by danilogiacomi** [comment]
ok, thanks
